services:
  _defaults:
    autowire: true
    autoconfigure: true

  Magicbart\ExternalReferenceBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,Entity,DependencyInjection,Migrations,Tests,Kernel.php}'
